# Generated by Django 3.2.4 on 2021-07-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210620_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=20)),
                ('project', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=10000)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
